### ISSUE TITLE
Cannot spawn giants with /spawnmob

### ISSUE THREAD

**Issue by mathias-gh** [tonibm19/Essentials#10]
EDIT: This is an issue with MCServer. I've sent a pull request to the MCServer repository.

I'm not sure if this is an issue with Essentials or MCServer, but I can't spawn giants with the /spawnmob command. It responds with "Unknown mob type". Giants seem to be implemented in MCServer like any other mob, as far as I know.

**Comment by tonibm19** [comment]
many thanks :+1:
